### ISSUE TITLE
Implement progression in "Docking" view

### ISSUE THREAD

**Issue by JohnnyQQQQ** [SimpleDocker-Group/Simpledocker#29]
Implement the functionality for the progressbar and the two arrow buttons.

Arrow back should be inactive when at position 0 of the Dockingplan
Arrow forward should be inactive when at the last position of the Dockingplan

**Comment by art-vande1ay** [comment]
also implemented in the docker view, should be moved to the viewmodel

**Comment by art-vande1ay** [comment]
pretty dirty but it works
