### ISSUE TITLE
Add input validation

### ISSUE THREAD

**Issue by JohnnyQQQQ** [SimpleDocker-Group/Simpledocker#31]
Add input validation for the "Order & Delivery" view

For each product in "bestellungen" the same product with the same amount should exist in "Lieferung"

**Comment by art-vande1ay** [comment]
More or less done. Should maybe moved from OrderView to the OrderViewModel

**Comment by JohnnyQQQQ** [comment]
move to viewmodel

**Comment by art-vande1ay** [comment]
moved to viewmodel
